model_name: t5-base
output_dir: models/t5_base_full
data_dir: data
train_filename: train.csv
batch_size: 1
eval_batch_size: 1
learning_rate: 3.0e-4
weight_decay: 0.01
epochs: 1
max_input_length: 512
max_target_length: 150
generation_max_length: 150
train_subset_size:
eval_subset_size:
val_ratio: 0.1
gradient_accumulation_steps: 8
warmup_steps: 500
logging_steps: 200
seed: 42
save_total_limit: 2
lr_scheduler_type: cosine_with_restarts

